Portfolio Setup Pull Request
brendalutiku/Portfolio-Setup pull request #2
Opened 2023-04-27 15:45 UTC by brendalutiku

In this project I made sure there are [no linter errors] using this link(https://github.com/microverseinc/linters-config):

In this project I used correct [GitHub Flow] using this link(https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md):

In this project i documented my work [in a professional way]using(https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md):

2023-04-27 17:07 UTC, divinecharlotte requested changes
Hi @brendalutiku     , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 
- Descriptive Pr 👍




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [ ] Kindly consider making your readme more descriptive by customizing the below section in the picture with the real data you used in your project 
<img width="758" alt="Screen Shot 2023-04-27 at 18 08 22" src="https://user-images.githubusercontent.com/60146030/234925583-55e6dc00-a996-4e0e-a161-1a06793eab1c.png">

1. add the tech stacks used in this project 
2. give all information in your get started section eg: link to clone, branch to checkout,.....

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 17:07 UTC, divinecharlotte commented on index.html
> +</section>
- [ ] kindly consider making the container of this whole code  a single section  tag as it is one section of your portfolio and remember sections should be made up of related content, like contact information  for best use of semantic tags
- [ ]  After that consider giving it a grid display to fulfill the below requirement
> The main container of the projects has a `display:grid`

2023-04-27 17:07 UTC, divinecharlotte commented on style.css
> +  flex-grow: 0;
- [ ] kindly consider making sure that the content of each project is aligned with the Flexbox so that when you want to lay a collection of items out in one direction or another it will be easily done and that will help you to have the same CSS on all projects cards without repeating yourself

2023-04-27 17:07 UTC, divinecharlotte commented on index.html
> +       <button class="press">See project</button>
- [ ] kindly consider designing your buttons based on the ones given in the Figma design and also consider giving your project card the equal margin left and right as given in Figma to make an exact duplicate of the provided design check the image below to see exactly what I meant 👇 
- your design 👇 
<img width="386" alt="Screen Shot 2023-04-27 at 18 43 56" src="https://user-images.githubusercontent.com/60146030/234932398-fa45d533-e4e3-4912-b3bb-14692dec739c.png">


- figma design 👇 
<img width="375" alt="Screen Shot 2023-04-27 at 18 40 36" src="https://user-images.githubusercontent.com/60146030/234932461-aee6275b-1740-4b01-8843-948b5250872b.png">

2023-04-27 17:07 UTC, divinecharlotte commented on index.html
> +                Myself</div>
- [ ] Kindly consider  making this title a header to fulfill the below requirement
> The title (e.g., "About myself") uses a header tag `hx`

2023-04-27 17:07 UTC, divinecharlotte commented on index.html
> +                <img src="./images/Frame 1.png" alt="" class="frame">
- [ ] Kindly consider adding those icons one by one not as a single picture cause each will contain a link to your social media while doing that remember to put each in a tag for them to be links also put into consideration that it `a` list of icons which means they have to be added in a `ul` tag and each in a `li` tag and that will help you to meet the below requirement 👇 
> The list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag)

2023-04-27 17:07 UTC, divinecharlotte commented on index.html
> +             </ul>
- [ ] Kindly consider adding the technology categories ("Languages", "Frameworks" and "Skills") in a `ul`, each of them in a `li` to make them a list of technologies not making each a `ul`

2023-04-27 17:07 UTC, divinecharlotte commented on index.html
> +<section class="about-me">
- [ ] Kindly consider that this section has the same margin and padding as the one given in the Figma design to deliver the expected output check the images below 👇  on which parts to fix 
- your design 👇 
<img width="284" alt="Screen Shot 2023-04-27 at 19 00 06" src="https://user-images.githubusercontent.com/60146030/234937061-46d5dd50-8a22-46c4-b1ef-48d904107f86.png">


- Figma design 👇 
<img width="224" alt="Screen Shot 2023-04-27 at 19 02 33" src="https://user-images.githubusercontent.com/60146030/234937268-2bb1d318-9a99-4ae8-bb1e-249ee8e4ee8b.png">

2023-04-27 23:19 UTC, brendalutiku commented
Hello am finding it hard adding a stack overflow on my readme could you
please send me the link to where i can get information so i can go through
it.Thank you.

On Thu, 27 Apr 2023 8:07 pm divine charlotte, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @brendalutiku <https://github.com/brendalutiku> ,
>
> Good job so far!
> You still need to work on some issues to go to the next project, but you
> are almost there!
> To Highlight 💯
>
>    - Descriptive Pr 👍
>
>
> <https://camo.githubusercontent.com/0c690ab997907a8c79afe7e695c891f6398cdbef93eaf8ce19f652ff321b54f8/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966>
> Required Changes ♻️
>
>    - Kindly consider making your readme more descriptive by customizing
>    the below section in the picture with the real data you used in your project
>
> [image: Screen Shot 2023-04-27 at 18 08 22]
> <https://user-images.githubusercontent.com/60146030/234925583-55e6dc00-a996-4e0e-a161-1a06793eab1c.png>
>
>    1. add the tech stacks used in this project
>    2. give all information in your get started section eg: link to clone,
>    branch to checkout,.....
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/brendalutiku/Portfolio-Setup/pull/2#discussion_r1179423971>
> :
>
> > +<h3 class="headings">Tonic</h3>
> +<img src="./images/Frame 2 (1).png" alt="" class="frame">
> +  <p>
> + A daily selection of privately personalized reads; no accounts or sign-ups required.
> +
> +
> +  </p>
> +  <ul class="tag">
> +        <li>
> +          <a href="#"><img src="./images/Tag (1).png" alt="html"></a>
> +        </li>
> +         <li>
> +          <a href="#"><img src="./images/Tag (2).png" alt="css"></a>
> +         </li>
> +         <li>
> +          <a href="#"><img src="./images/Tag (3).png" alt="javascript"></a>
> +         </li>
> +         </ul>
> +
> +
> +      <div class="buttons">
> +       <button class="press">See project</button>
> +      </div>
> +</section>
> +<section class="cardworks-two">
> +  <img src="./images/Snapshoot Portfolio (2).png" alt="" class="snapshoot">
> +  <div class="left-blockone"></div>
> +
> +   <h4 class="heading-two">Multi-post stories</h4>
> +
> +
> +<img src="./images/Frame 2 (1).png" alt="" class="frame">
> +  <p>
> +    A daily selection of privately personalized reads; no accounts or sign-ups required.
> +  </p>
> +
> +  <ul class="tag">
> +        <li>
> +          <a href="#"><img src="./images/Tag (1).png" alt="html"></a>
> +        </li>
> +         <li>
> +          <a href="#"><img src="./images/Tag (2).png" alt="css"></a>
> +         </li>
> +         <li>
> +          <a href="#"><img src="./images/Tag (3).png" alt="javascript"></a>
> +         </li>
> +         </ul>
> +      <div class="buttons">
> +       <button class="press">See project</button>
> +      </div>
> +
> +</section>
> +<section class="cardworks-three">
> +  <img src="./images/Snapshoot Portfolio (3).png" alt="" class="snapshoot">
> +  <div class="left-blocktwo"></div>
> +  <h5 class="headings">Tonic</h5>
> +<img src="./images/Frame 2 (1).png" alt="" class="frame">
> +  <p>
> +   A daily selection of privately personalized reads; no accounts or sign-ups required.
> +  </p>
> +   <ul class="tag">
> +        <li>
> +          <a href="#"><img src="./images/Tag (1).png" alt="html"></a>
> +        </li>
> +         <li>
> +          <a href="#"><img src="./images/Tag (2).png" alt="css"></a>
> +         </li>
> +         <li>
> +          <a href="#"><img src="./images/Tag (3).png" alt="javascript"></a>
> +         </li>
> +         </ul>
> +      <div class="buttons">
> +      <button class="press">See project</button>
> +      </div>
> +</section>
> +<section class="cardworks-four">
> +  <img src="./images/Snapshoot Portfolio (4).png" alt="" class="snapshoot">
> +  <div class="left-blockthree"></div>
> +  <h6 class="heading-two">Multi-Post Stories</h6>
> +  <img src="./images/Frame 2 (1).png" alt="" class="frame">
> +  <p>
> +  A daily selection of privately personalized reads; no accounts or sign-ups required.
> +  </p>
> +<ul class="tag">
> +        <li>
> +          <a href="#"><img src="./images/Tag (1).png" alt="html"></a>
> +        </li>
> +         <li>
> +          <a href="#"><img src="./images/Tag (2).png" alt="css"></a>
> +         </li>
> +         <li>
> +          <a href="#"><img src="./images/Tag (3).png" alt="javascript"></a>
> +         </li>
> +         </ul>
> +
> +      <div class="buttons">
> +       <button class="press">See project</button>
> +      </div>
> +</section>
> +</section>
>
>
>    - kindly consider making the container of this whole code a single
>    section tag as it is one section of your portfolio and remember sections
>    should be made up of related content, like contact information for best use
>    of semantic tags
>    - After that consider giving it a grid display to fulfill the below
>    requirement
>
> The main container of the projects has a display:grid
>
> ------------------------------
>
> In style.css
> <https://github.com/brendalutiku/Portfolio-Setup/pull/2#discussion_r1179432070>
> :
>
> > +.cardworks-one {
> +  box-sizing: border-box;
> +
> +  /* Auto layout */
> +  flex-direction: column;
> +  align-items: center;
> +  padding: 16px;
> +  gap: 16px;
> +  width: 327px;
> +  height: 552px;
> +  margin: 40px;
> +
> +  /* Neutrals/ N0 */
> +  background: #ffff;
> +
> +  /* Neutrals/ N40 */
> +  border: 1px solid #dfe1e6;
> +  border-radius: 16px;
> +
> +  /* Inside auto layout */
> +  flex: none;
> +  order: 0;
> +  flex-grow: 0;
>
>
>    - kindly consider making sure that the content of each project is
>    aligned with the Flexbox so that when you want to lay a collection of items
>    out in one direction or another it will be easily done and that will help
>    you to have the same CSS on all projects cards without repeating yourself
>
> ------------------------------
>
> In index.html
> <https://github.com/brendalutiku/Portfolio-Setup/pull/2#discussion_r1179444131>
> :
>
> > +  </p>
> +  <ul class="tag">
> +        <li>
> +          <a href="#"><img src="./images/Tag (1).png" alt="html"></a>
> +        </li>
> +         <li>
> +          <a href="#"><img src="./images/Tag (2).png" alt="css"></a>
> +         </li>
> +         <li>
> +          <a href="#"><img src="./images/Tag (3).png" alt="javascript"></a>
> +         </li>
> +         </ul>
> +
> +
> +      <div class="buttons">
> +       <button class="press">See project</button>
>
>
>    - kindly consider designing your buttons based on the ones given in
>    the Figma design and also consider giving your project card the equal
>    margin left and right as given in Figma to make an exact duplicate of the
>    provided design check the image below to see exactly what I meant 👇
>    - your design 👇
>
> [image: Screen Shot 2023 [...]

2023-04-28 11:01 UTC, topeogunleye requested changes
Hi @brendalutiku, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* No linter errors. :heavy_check_mark:
* Followed Github flow :heavy_check_mark:

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- [ ]  Next time, and for future commits, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Bad Commit Messages :x:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/52934128/235125436-6fa216e0-68d4-428c-ab69-741fc4cc008e.png">

### ✔️ Good Commit Messages: ✔️
✔️  Add fix for dark mode toggle state
✔️  Update README file.
✔️  Add styles to h1.

- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

- [ ] It seems like you have named your project branch as PortfolioVersion. While this is a descriptive name, it does not necessarily convey that the project does not use a particular feature or action.

- When naming a project branch, it's important to choose a name that accurately reflects the contents of the branch. In this case, PortfolioVersion indicates that the branch is related to a portfolio Version. However, it doesn't explicitly convey any information about what the branch does or doesn't use.

- If there is a specific feature or action that your project branch does not use, it might be helpful to include that in the name. For example, if your branch finishes portfolio mobile version, you could name it finished-mobile-version

- [ ] I noticed that the title of your pull request is "Portfolio Setup Pull Request", which does not seem to match the milestone you have submitted.

For future pull requests, In order to keep the pull request organized and easy to understand for the reviewers, it is recommended to have the pull request title named after the feature or action it addresses, which in this case would be "Finish mobile version of Portfolio". This helps everyone involved to quickly understand the purpose of the pull request.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 11:01 UTC, topeogunleye commented on index.html
> +<div class="works">
- [ ] As suggested by the previous reviewer, the container of your works should be a section tag. see an example below

## EXAMPLE
```
<div class="works">
  <-- your projects go here -->
</div>
```

2023-04-28 11:01 UTC, topeogunleye commented on style.css
> +.press {
- [ ] [OPTIONAL] I kindly suggest that you add the different button interactions including hover, active (when it's pressed), disabled, and enable (default state) as shown in the Figma template below:

![Screenshot from 2022-04-27 19-12-50](https://user-images.githubusercontent.com/52934128/165592912-7d8bf224-8e6b-467d-bb19-cf63cd2b40fd.png)

the button on the pressed state has the `background: #2230D2;` and on hover has the `background: #6070FF;`

### EXAMPLE:
**for pressed state**
```
button:active {
   background-color: #2230D2;
}
```
**for hover state**
```
button:hover {
    background-color: #6070FF;
}
```

2023-04-28 11:01 UTC, topeogunleye commented on index.html
> +<div class="works">
- [ ] As suggested by the previous reviewer, I kindly suggest that you ensure that your projects have the same margin on left and right. Kindly see a comparison below:


| Your Design  | Figma |
| ------------- | ------------- |
| <img width="308" alt="image" src="https://user-images.githubusercontent.com/52934128/235118187-2ce3ec6e-dc8c-48bd-afa0-77d788dba5b9.png">  | <img width="257" alt="image" src="https://user-images.githubusercontent.com/52934128/235118806-1582551a-41d1-424b-be68-551c09d439a1.png">  |

2023-04-28 11:01 UTC, topeogunleye commented on index.html
> +            <header>About
- [ ] As suggested by the previous reviewer. I kindly suggest that you make use of any header from `h2` tp `h6` as a tag for your `About Myself` text here.

## EXAMPLE`
✔️ 
`<h2>About Myself</h2>`

❌ 
`<header>About Myself</header>
`

2023-04-28 11:01 UTC, topeogunleye commented on index.html
> +        <div class="box">
- [ ] As suggested by the previous reviewer, I kindly suggest that you also use a two level nested list. i.e Make this `div` a `ul`, and then make nest the language, framework, and skills `ul's` in it's `li's`.

## EXAMPLE
```
   <ul>
        <li class="languague">
              <ul>
                  <li><a href="#">JavaScript</a></li>
                  <li><a href="#">HTML</a>
                  <li><a href="#">CSS</a>
             </ul>
         </li>
          <li class="framework">
              <ul>
                  <li><a href="#">Bootstrap</a></li>
                  <li><a href="#">Ruby on Rails</a>
                  <li><a href="#">RSPEC</a>
             </ul>
         </li>
            <li class="skills">
              <ul>
                  <li><a href="#">Code Kit</a></li>
                  <li><a href="#">GitHub</a>
                  <li><a href="#">Codepen</a>
             </ul>
         </li>                                     
</ul>
```

2023-04-28 11:01 UTC, topeogunleye commented on index.html
> +            <header>About
- [ ] As suggested by the previous reviewer. I kindly suggest that you ensure that your `About Myself` text here has enough margin on the bottom.

| Your About Text  | Figma Design |
| ------------- | ------------- |
| <img width="323" alt="image" src="https://user-images.githubusercontent.com/52934128/235121732-729b6c8e-2c65-4b28-955f-1787b704aadd.png"> | <img width="255" alt="image" src="https://user-images.githubusercontent.com/52934128/235121823-5e843eea-6a4f-4f05-a194-727b615202b9.png">  |

2023-04-28 14:58 UTC, braincee approved these changes
Hi @brendalutiku 👋  , I am @braincee, your Code Reviewer.

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![youre-approved-shirley-auto-group](https://user-images.githubusercontent.com/78104544/226852457-95ef4c1d-5d51-4f76-abd8-1fdc06b89e77.gif)

OPTIONAL CHANGES
---

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @braincee._

---

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-28 19:28 UTC, merged